apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-creds
  namespace: monitoring # Best practice: keep o11y in its own namespace
type: Opaque
stringData:
  # K8s will automatically base64 encode this for you
  admin-password: "encrypted-value-from-github"